### PR TITLE
13 dna api unit tests

### PR DESCRIPTION
**Pull request by murrayjbrown**
PR for issues #13 & #14 .

Unit tests for DNA API are scaffolded but disabled by imperative assertion gates, awaiting refinement once functions to be tested are sufficiently implemented.

### CODE REVIEW

**Comment by Connoropolous** [comment]
Hey @murrayjbrown this is an awesome start on a contribution! Thankyou! 

A decision was JUST made and implemented to re-integrate hdk-rust as a folder within holochain-rust. 

Do you think it could be possible to make revisions, and re-open a PR over there? 

Sorry again, and I certainly don't believe it will be moving any time again soon.

**Comment by Connoropolous** [comment]
Also, I think that having them integrated will actually prove to be a much easier development and PR workflow than it currently is with these two split out. So here's the subfolder where it is:
https://github.com/holochain/holochain-rust/tree/develop/hdk-rust

**Comment by murrayjbrown** [comment]
Hey @Connoropolous, no worries! Will do. I'll get right on it tomorrow. I was about to look at what's up next (after this, now) to work on… any suggestions?

**Comment by Connoropolous** [comment]
Ok cool. 🙏 

Before I answer your question, maybe I could ask you one, to get to know you a little better. What type of contribution, or focus, is it that you'd most like to make? 
There is stuff around the command line tools, in addition to the hdk-rust and core, in process

**Comment by murrayjbrown** [comment]
@Connoropolous, thanks for asking. I guess in order of preference it would be: core, APIs, tools. I've always been more interested in application enabling infrastructure than applications themselves.

**Comment by Connoropolous** [comment]
Right on :)

Then I will see what I can do to help you find stuff in core to try out.

For context, I am more responsible for documentation than code, but I have close involvement with the dev team and the workflow

**Comment by murrayjbrown** [comment]
Awesome, thanks! :-)

**Comment by murrayjbrown** [comment]
Hey @Connoropolous, just looking at gathering commits together for a new PR on holochain-rust/hdk-rust. As hdk-rust has not been included as a sub-repo within a holochain-rust monorepo, it doesn't look as though commit history is being preserved so should I just aggregate past commits as a single diff changeset commited against the current state? Also, how are issues being preserved? Should I use cross-repo references to issues #13 & #14 in this repo or are the HDK issues being migrated to holochain-rust?

**Comment by Connoropolous** [comment]
A lot of the open issues here are duplicates, in a sense, of ones open in holochain-rust, given that they just mean to implement a function in the hdk that is now implemented in core. 

This flow will likely change now to just being a matter of implementing it within hdk-rust at the same time as in core, meaning the holochain-rust tickets related to implement core api functions just grow in scope.

**Comment by Connoropolous** [comment]
And to your question about commit history... yes. I think aggregate the past cmomits as a single diff. Not ideal, but it seems the only way this time around

**Pull request closed without merging**
